
name: Deploy to ECS
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  builddeploytoecs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code from repo
        uses: actions/checkout@v3

      - name: setup java and maven environment
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: upload to github packages
        run: mvn --batch-mode deploy
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: package with maven
        run: mvn package

      - name: authenticate to aws account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag and push
        id: build-image
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REPOSITORY: borisrepo
          IMAGE_TAG: ${{github.sha}}
        run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
            echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
           task-definition: task-definition.json
           container-name: xashy-image
           image: ${{ steps.build-image.outputs.image }}
                
          ### github action should update the service with the lastes task-definition revision. Makue sure you change the name of the cluster and service name 
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
            task-definition: ${{ steps.task-def.outputs.task-definition }}
            service: mbuen-pp
            cluster: myclustermb
            wait-for-service-stability: true 
              